name: Sync Translations

on:
  push:
    branches:
      - main
    paths:
      - 'mtimer/**'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync translations to MTimer
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
        with:
          source_file: '${{ github.workspace }}/mtimer'
          destination_repo: 'MUtils-MC/MTimer'
          destination_folder: 'data/language'
          user_email: 'miraculixxyt@gmail.com'
          user_name: 'MiraculixxT'
          commit_message: 'Sync all translations'
